### ISSUE TITLE
Static response methods not working

### ISSUE THREAD

**Issue by ymoreiratiti** [5c077m4n/http-responder#15]
When trying to use static method, the package return:
```TypeError: hr.failedDependency is not a function```

Step to reproduce error:
1. Create a snippet:
```javascript
const hr = require('http-responder')
const objError = hr.failedDependency('Error on external API')
console.log('objError', objError)
```

2. Run it with http-responder@2.0.22 version. It work's
```powershell
C:\temp\teste>npm i http-responder@2.0.22
npm WARN teste@1.0.0 No description
npm WARN teste@1.0.0 No repository field.

+ http-responder@2.0.22
updated 1 package and audited 1 package in 1.19s
found 0 vulnerabilities


C:\temp\teste>node main.js
objError s [Error]: ERROR LABEL
    at Function.s.<computed> [as failedDependency] (C:\temp\teste\node_modules\http-responder\dist\index.js:4:2952)
    at Object.<anonymous> (C:\temp\teste\main.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  statusCode: 424,
  message: 'ERROR LABEL',
  data: undefined,
  _isHttpRes: true
}
```

3. Run it with http-responder@latest version. It fail
```powershell
C:\temp\teste>npm i http-responder@latest
npm WARN teste@1.0.0 No description
npm WARN teste@1.0.0 No repository field.

+ http-responder@2.1.6
updated 1 package and audited 1 package in 0.556s
found 0 vulnerabilities


C:\temp\teste>node main.js
C:\temp\teste\main.js:2
const objError = hr.failedDependency('ERROR LABEL')
                    ^

TypeError: hr.failedDependency is not a function
    at Object.<anonymous> (C:\temp\teste\main.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by 5c077m4n** [comment]
Thank you for the catch, I fixed this error in v2.2.0.
